server:
  port: ${port:4444}

spring:
   datasource:
       driverClassName: org.postgresql.Driver
       url: jdbc:postgresql://localhost:5432/ubigeo-project
       username: postgres
       password: postgres

eureka:  
  client:
    serviceUrl:
      defaultZone: http://localhost:${port:8010}/eureka/

logging:  
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
