---
server:
  port: 8002
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ecavalie/ms-atlaris-config-repo
          searchPaths: ms-atlaris-config-apps

logging:  
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
